FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install && \
    npm ci && \
    npm install -g @nestjs/cli && \
    ln -s /usr/local/bin/nest /usr/bin/nest

COPY . .

COPY nest-cli.dev.json nest-cli.json

EXPOSE 4001